name                 'fhuertas-tomcat7'
version              '0.0.1'
summary              'Manual (without package system) installation of tomcat7'
source               'https://github.com/yunxao/puppet_manual_jre_install'
project_page         'https://github.com/yunxao/puppet_manual_jre_install'
description          'Manual (without package system) installation of tomcat7'
license              'Apache 2.0'
author               'Francisco Huertas Ferrer'


